### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by init5-SF** [cwolff411/powerob#3]
Any ideas? :) 
```
root@kali:/opt/tools/powerob# python3 powerob.py obfuscate revnew.ps1 revx.ps1 

       ___                        ___ _     
      / _ \_____      _____ _ __ /___| |__  
     / /_)/ _ \ \ /\ / / _ | '__//  /| '_ \ 
    / ___| (_) \ V  V |  __| | / \_//| |_) |
    \/    \___/ \_/\_/ \___|_| \___/ |_.__/ 

            author: Cory Wolff <visnet>
            company: Layer 8 <layer8security.com>
    
---------------------------------------------------------------------------

[+] Loading the Powershell script
[+] Locating functions
[-] No Functions Found. Exiting...
Traceback (most recent call last):
  File "powerob.py", line 120, in find_functions
    exit()
  File "/usr/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "powerob.py", line 316, in <module>
    PowerOb()
  File "powerob.py", line 192, in __init__
    getattr(self, args.command)()
  File "powerob.py", line 205, in obfuscate
    functions = find_functions(args.inputfile)
  File "powerob.py", line 126, in find_functions
    print(color("[-] Unexpected error:" + sys.exc_info()[0]))
TypeError: can only concatenate str (not "type") to str

```

**Comment by cwolff411** [comment]
So it looks like there aren't any functions in that ps1 that you're trying to obfuscate. As of right now, powerob will only obfuscate functions. That type error is actually an error with my error handling 😮

**Comment by cwolff411** [comment]
Updated it to fix the error with error handling.
